### ISSUE TITLE
There is a probability that saving annotations may fail, resulting in annotation loss

### ISSUE THREAD

**Issue by Soul-Code** [SixK/coco-annotator-ng#10]
The ng version has shown significant speed improvements compared to the original version—great work on this! However, I’ve encountered an issue that occurs randomly. When this issue arises, I’m unable to switch tools or continue annotating. The annotations I’ve already completed disappear.

Whenever I try to switch tools, the following error appears in the console:

![image](https://github.com/user-attachments/assets/065fa12d-3dac-468a-ac6b-40d6eeed019d)

When I try to save, the console will get same error.

Do you have any ideas about this?

**Comment by Soul-Code** [comment]
![image](https://github.com/user-attachments/assets/8f077ab6-34a2-4f2e-b89f-d5b5aed5ea82)
Added some additional information

**Comment by SixK** [comment]
Thank's for report. 
I actually don't find a way to reproduce the problem.

If looking at warning "@ Annotator.vue:461", it seem's I have a problem relative to setActiveTool() function.
Only possible problem could happen in "src/composables/toolBar/tools.js" file where tool passed as argument is a variable.
But if looking at logs, tool name seem's to be defined before.
So it could be a race condition on tool.name passed as argument of setActiveTool() while DOM is being refreshed ?

I will keep on trying to reproduced the problem.
If you find a way to reproduce it, it could help me.

**Comment by SixK** [comment]
I have a similar error/warning, even if it's not exactly the same, playing with save button and "Select" and "Brush" shortcuts.
Does your problem also happen when changing tool using shortcuts ?
![image](https://github.com/user-attachments/assets/27f31498-d778-4b07-99a5-c385f0d7417c)
It will not be easy to fix

**Comment by SixK** [comment]
At least, I fixed a bug in SelectTool.vue (https://github.com/SixK/coco-annotator-ng/commit/6abe3865d9e6d5a1c67caf8c28311b10e5cb7620)
in this code, I was not checking compoundPath exists:
```
        if (hover.value.annotation && hover.value.annotation.compoundPath) {
          hover.value.annotation.compoundPath.selected = false;
        }
```
But this mistake, may not be the root cause of your problem.

To reproduce error I had, create a new empty annotation, then press 'b' key.

**Comment by Soul-Code** [comment]
Thank you very much for your reply and fix !
Using shortcut modification tools can also trigger this issue. Is this related to me using dev env (docker-compose.dev.yml) to start the project?
By the way,  When I deployed using the docker-compose.yml, I found that refreshing the page on any route (except for the root route) would result in a 404 error.

Refer to #11

**Comment by Soul-Code** [comment]
> Thank you very much for your reply and fix ! Using shortcut modification tools can also trigger this issue. Is this related to me using dev env (docker-compose.dev.yml) to start the project? By the way, When I deployed using the docker-compose.yml, I found that refreshing the page on any route (except for the root route) would result in a 404 error.
> 
> Refer to #11

After applying the changes in https://github.com/SixK/coco-annotator-ng/commit/2eaa1067efd8cf3e7186c5896fb6392bddbdc166 , I switched to using the docker-compose.yml in production mode to start the project. This seems to have resolved the issue, and so far, I haven't encountered any similar problems when running in production mode.

I really appreciate your help!👍
