### ISSUE TITLE
Dataset Sharing Clears the users Field

### ISSUE THREAD

**Issue by Soul-Code** [SixK/coco-annotator-ng#13]
Description
When sharing a dataset with other users, the users field of dataset_model is cleared.

Expected Behavior
The users field should be updated to reflect the current selection rather than being cleared.

Steps to Reproduce

Share a dataset with other users follow the steps.

![30a8efda76e97036a31b9588cc53a6a](https://github.com/user-attachments/assets/9f7c98ed-3fff-4c6c-af79-7608a9c0ba1c)
![image](https://github.com/user-attachments/assets/46028015-2b26-4c27-abbc-255f04eb2a36)

After sharing, the users field is cleared. 
![image](https://github.com/user-attachments/assets/31f75cd8-cec2-458d-93b9-62a23d04f587)

**Comment by SixK** [comment]
It's a functionality I never used, 
I have to spend time to understand how it is working in original JsBroks code and fix it.
Thank's for the report.

**Comment by SixK** [comment]
Share button should be fixed by commit https://github.com/SixK/coco-annotator-ng/commit/ddadb95ee6971f71c8aa46ca436394f5ae84dd10
This commit should also fix Keypoints edges management in KeypointsDefinition.

**Comment by Soul-Code** [comment]
I have tested the fix, and the issue has been resolved. Thank you for your hard work and prompt response!
