### ISSUE TITLE
 Space and Backspace Shortcuts Not Working

### ISSUE THREAD

**Issue by Soul-Code** [SixK/coco-annotator-ng#16]
![image](https://github.com/user-attachments/assets/163a68a3-80da-4412-b70f-5600a9f16a0b)

The **Space** and **Backspace** keys are not functioning in the application. 

By the way, the close button (×) at the top right corner of the interface seems to have an incorrect position and style. However, this issue is not critical.

**Comment by SixK** [comment]
Space and backspace problem to create or remove annotations should be fixed by commit 47f7c72c0dfc4de4509eb7639fdf4788526e4ef2  
Close button position and aspect should be fixed by commit bd3402a4d71a03389bd648d6deb78c256346b15d  

Thank's for bugs reports.

**Comment by Soul-Code** [comment]
I have confirmed that the issue mentioned has been resolved. Thank you!
