### ISSUE TITLE
Pagination not Synchronized

### ISSUE THREAD

**Issue by qiubinyang** [SixK/coco-annotator-ng#17]
When browsing the Dataset, the two paginations at the top and bottom of the page are not synchronized. This often leads to misjudgment of the current page number.

Finally, I see someone has picked up this project. Hope you can help fix this problem. Thank you.

**Comment by SixK** [comment]
Thank's for bug report, pagination synchronization should be fixed by this commit fb7031c0e61234463f1dbc31a9f3f05b71bc8b97

**Comment by qiubinyang** [comment]
So quick! Thanks!
