### ISSUE TITLE
Build image error.

### ISSUE THREAD

**Issue by YTed** [SixK/coco-annotator-ng#2]
Hi, I clone your repo and try to build image and run as described in README.md, error occured:

> > [workers 3/4] RUN apt-get update && apt-get install --no-install-recommends -y libsm6 libxrender1 libfontconfig1 libgl1  libglib2.0-0 &&           apt clean && rm -rf /var/lib/apt/lists/*:
> 0.695 Ign:1 http://deb.debian.org/debian stretch InRelease
> 0.809 Ign:2 http://deb.debian.org/debian stretch-updates InRelease
> 0.922 Ign:3 http://deb.debian.org/debian stretch Release
> 1.276 Ign:4 http://deb.debian.org/debian stretch-updates Release
> 1.714 Ign:5 http://security.debian.org/debian-security stretch/updates InRelease
> 1.723 Ign:6 http://deb.debian.org/debian stretch/main all Packages
> 1.837 Ign:7 http://deb.debian.org/debian stretch/main amd64 Packages
> 1.838 Ign:8 http://security.debian.org/debian-security stretch/updates Release
> 1.951 Ign:9 http://deb.debian.org/debian stretch-updates/main all Packages
> 1.960 Ign:10 http://security.debian.org/debian-security stretch/updates/main all Packages
> 2.065 Ign:11 http://deb.debian.org/debian stretch-updates/main amd64 Packages
> 2.324 Ign:12 http://security.debian.org/debian-security stretch/updates/main amd64 Packages
> 2.426 Ign:6 http://deb.debian.org/debian stretch/main all Packages
> 2.465 Ign:10 http://security.debian.org/debian-security stretch/updates/main all Packages
> 2.543 Ign:7 http://deb.debian.org/debian stretch/main amd64 Packages
> 2.597 Ign:12 http://security.debian.org/debian-security stretch/updates/main amd64 Packages
> 2.660 Ign:9 http://deb.debian.org/debian stretch-updates/main all Packages
> 2.731 Ign:10 http://security.debian.org/debian-security stretch/updates/main all Packages
> 2.776 Ign:11 http://deb.debian.org/debian stretch-updates/main amd64 Packages
> 2.847 Ign:12 http://security.debian.org/debian-security stretch/updates/main amd64 Packages
> 2.889 Ign:6 http://deb.debian.org/debian stretch/main all Packages
> 2.963 Ign:10 http://security.debian.org/debian-security stretch/updates/main all Packages
> 3.016 Ign:7 http://deb.debian.org/debian stretch/main amd64 Packages
> 3.129 Ign:9 http://deb.debian.org/debian stretch-updates/main all Packages
> 3.332 Ign:12 http://security.debian.org/debian-security stretch/updates/main amd64 Packages
> 3.387 Ign:11 http://deb.debian.org/debian stretch-updates/main amd64 Packages
> 3.454 Ign:10 http://security.debian.org/debian-security stretch/updates/main all Packages
> 3.499 Ign:6 http://deb.debian.org/debian stretch/main all Packages
> 3.569 Ign:12 http://security.debian.org/debian-security stretch/updates/main amd64 Packages
> 3.690 Ign:10 http://security.debian.org/debian-security stretch/updates/main all Packages
> 3.755 Ign:7 http://deb.debian.org/debian stretch/main amd64 Packages
> 3.811 Err:12 http://security.debian.org/debian-security stretch/updates/main amd64 Packages
> 3.811   404  Not Found
> 3.884 Ign:9 http://deb.debian.org/debian stretch-updates/main all Packages
> 3.996 Ign:11 http://deb.debian.org/debian stretch-updates/main amd64 Packages
> 4.125 Ign:6 http://deb.debian.org/debian stretch/main all Packages
> 4.490 Ign:7 http://deb.debian.org/debian stretch/main amd64 Packages
> 4.602 Ign:9 http://deb.debian.org/debian stretch-updates/main all Packages
> 4.714 Ign:11 http://deb.debian.org/debian stretch-updates/main amd64 Packages
> 4.827 Ign:6 http://deb.debian.org/debian stretch/main all Packages
> 5.253 Err:7 http://deb.debian.org/debian stretch/main amd64 Packages
> 5.253   404  Not Found
> 5.366 Ign:9 http://deb.debian.org/debian stretch-updates/main all Packages
> 5.477 Err:11 http://deb.debian.org/debian stretch-updates/main amd64 Packages
> 5.477   404  Not Found
> 5.487 Reading package lists...
> 5.523 W: The repository 'http://deb.debian.org/debian stretch Release' does not have a Release file.
> 5.523 W: The repository 'http://deb.debian.org/debian stretch-updates Release' does not have a Release file.
> 5.523 W: The repository 'http://security.debian.org/debian-security stretch/updates Release' does not have a Release file.
> 5.523 E: Failed to fetch http://deb.debian.org/debian/dists/stretch/main/binary-amd64/Packages  404  Not Found
> 5.523 E: Failed to fetch http://deb.debian.org/debian/dists/stretch-updates/main/binary-amd64/Packages  404  Not Found
> 5.523 E: Failed to fetch http://security.debian.org/debian-security/dists/stretch/updates/main/binary-amd64/Packages  404  Not Found
> 5.523 E: Some index files failed to download. They have been ignored, or old ones used instead.
> ------
> failed to solve: process "/bin/sh -c apt-get update && apt-get install --no-install-recommends -y libsm6 libxrender1 libfontconfig1 libgl1  libglib2.0-0 &&           apt clean && rm -rf /var/lib/apt/lists/*" did not complete successfully: exit code: 100
 
How should I fixed it?

Environment: 
OS version: CentOS 7, Docker version: 24.0.6

**Comment by SixK** [comment]
Hi,

As build seem's to try to get debian stretch packages, I would say you are using official jsbroks docker image (docker.io/jsbroks/coco-annotator:python-env).
coco-annotator-ng is using an image based on bookworm.

You have to first build base image "docker.io/jsbroks/coco-annotator:python-env":
`bash build_gpu.sh`

Then you can build components docker images using one of this command depending on your needs:
```
docker-compose -f docker-compose.dev.yml build
or
docker-compose -f docker-compose.gpu.yml build
or
docker-compose -f docker-compose.build.yml build
```
I have to modify the Readme to tell to first run "bash ./build_gpu.sh" command. 
Sorry for confusion.

**Comment by SixK** [comment]
Building images procédure is now fixed in Readme by this commit:
https://github.com/SixK/coco-annotator-ng/commit/f6c73fcb1e37ebd9ffdca47e2bac44abc72e4c47
