### ISSUE TITLE
Bounding Box annotation

### ISSUE THREAD

**Issue by pschlein** [SixK/coco-annotator-ng#3]
Selecting BBox Tool creates additional annotations on top of the already existing empty annotation

Steps to reproduce:
1, open an image to annotate
2, select + icon for a category
-> "Select Tool" activated by default
-> Category shows an Empty annotation
3. select BBox Tool

Result:
Additionally to the empty annotation, a new annotation with the BBox has been created. The empty annotation needs to be removed manually

Expected Result
Switching the Tool should apply to the empty yet created annotation like in original version of coco-annotator

**Comment by SixK** [comment]
Thanks for this report.
Problem should be fixed with this commit ce64435ee6b7e8bd2f1259fbd71464184b5dc2ba
