### ISSUE TITLE
COCO Export returns Undefined, Export doesn't include Mask Images

### ISSUE THREAD

**Issue by chancecardona** [SixK/coco-annotator-ng#5]
Hi again, just noting a few things about the COCO export process. 

The first issue is a bug: when I press the "Download COCO" button from the dataset dropdown, I get a json file which simply contains the word "undefined". If instead I go to the dataset page and say "Export COCO" then go to the "Exports" tab though, the exported json works fine.

The next thing is that there are no annotated images exported. (this may be a feature request, not sure)
I can click on the three dots for an image in the dataset and click "Download Image and COCO", but this option only downloads the unlabelled image. Is there a way we can download the annotated images (either the individual masks or the composite image)? 
It would be great if the export could download the normal image, the annotated image, for each image in a dataset and then the annotations json for that dataset. I am looking into this portion but am still unfamiliar myself.

**Comment by SixK** [comment]
2 bugs confirmed comparing with original jsbroks coco-annotator :
- "Download COCO" return a file containing "undefined" value
- "Download Image and COCO" does not return image

Exporting image with annotation shoud be possible to implement, 
we already generate thumbnail images with annotations.
I'll try to implement it.

**Comment by SixK** [comment]
The two Download COCO bugs should be fixed by commit bf8e2487a87532b1d29b5c9781d14a3c010741f8
I have to look to add possibility to export segmented images.

**Comment by zhouquan03** [comment]
> The two Download COCO bugs should be fixed by commit [bf8e248](https://github.com/SixK/coco-annotator-ng/commit/bf8e2487a87532b1d29b5c9781d14a3c010741f8) I have to look to add possibility to export segmented images.

Has this commit been merged into main branch?

**Comment by SixK** [comment]
Yes commit for 2 bugs is already merged in main branch.
In fact, as I work alone, I only work in main branch. I know it's a bad habit ;)

Enhancement to export segmented images is to be coded, 
but it seem's not that difficult to do.

**Comment by SixK** [comment]
Commit 8d167d1af34d08d95e6ee36a2fd72050805c5d13 should add possibility to export segmented image.
Button "Download segmented Image" has been added under "Download Image & COCO" button on image card.

**Comment by chancecardona** [comment]
Sweet these changes are great! I can confirm that the COCO downloading bugs have been resolved. The new "Download Segmented Image" works good for me. :champagne:
