### ISSUE TITLE
Unable to move the bbox 

### ISSUE THREAD

**Issue by JinDing123** [SixK/coco-annotator-ng#8]
Hello. Hello. One problem I found is that in the vue2 version of coco-annotator, the bbox can be moved with SelectTool, but the Coco-annotator-ng can't seem to move the bbox

**Comment by SixK** [comment]
Hi, JinDing123, 

Your right, it works in my dev directory, 
but doesn't work in my release directory.

After few tests, it seem's to not work with first class of label list, 
but seem's to work fine with others classes.

**Comment by SixK** [comment]
Should be fixed with this commit https://github.com/SixK/coco-annotator-ng/commit/aaf83150f9fc791255a61949263103efb621455e

I had a wrong test on categoryId when checking if object is a BBox.

Thank's for the report

**Comment by JinDing123** [comment]
You're welcome, and thanks for fixing the bug
